# Generated by Django 2.2 on 2019-04-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepworkapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
